"""Polymarket API, CLOB, Data, and WebSocket adapters."""

from fdv_trader.infra.polymarket.auth import (
    DerivedApiCredentials,
    PolymarketCredentials,
    PolymarketOrderExecutionClient,
    PolymarketTradingClient,
    build_order_execution_client,
    build_trading_client,
)
from fdv_trader.infra.polymarket.clob_client import ClobClient
from fdv_trader.infra.polymarket.data_client import DataClient
from fdv_trader.infra.polymarket.gamma_client import GammaClient
from fdv_trader.infra.polymarket.schemas import (
    BalanceAllowanceDTO,
    ClobFillDTO,
    ClobOrderDTO,
    ClobOrderRequest,
    ClobOrderbookDTO,
    DataPositionDTO,
    DataTradeDTO,
    GammaEventDTO,
    GammaMarketDTO,
    OrderbookLevelDTO,
    PolymarketAuthError,
    PolymarketClientError,
    PolymarketRateLimitError,
    PolymarketResponseError,
    PolymarketRestClientBase,
    PolymarketSubscriptionChannel,
    PolymarketTimeoutError,
    PolymarketTransportError,
    PolymarketWebSocketError,
    RawMarketEvent,
    WebSocketMessage,
    WebSocketSubscription,
    build_market_subscription_request,
    build_user_subscription_request,
    data_position_to_domain_position,
    data_trade_to_domain_fill,
    gamma_event_to_raw_market_events,
    normalize_balance_allowance_payload,
    normalize_fill_payload,
    normalize_gamma_event,
    normalize_gamma_market,
    normalize_order_payload,
    normalize_orderbook_payload,
    normalize_position_payload,
    normalize_trade_payload,
    orderbook_payload_to_snapshot,
    orderbook_to_domain_snapshot,
    parse_ws_message,
)
from fdv_trader.infra.polymarket.ws_client import PolymarketWebSocketClient

__all__ = [
    "ClobClient",
    "BalanceAllowanceDTO",
    "ClobFillDTO",
    "ClobOrderDTO",
    "ClobOrderRequest",
    "ClobOrderbookDTO",
    "DataClient",
    "DataPositionDTO",
    "DataTradeDTO",
    "DerivedApiCredentials",
    "GammaClient",
    "GammaEventDTO",
    "GammaMarketDTO",
    "OrderbookLevelDTO",
    "PolymarketCredentials",
    "PolymarketAuthError",
    "PolymarketClientError",
    "PolymarketOrderExecutionClient",
    "PolymarketRateLimitError",
    "PolymarketResponseError",
    "PolymarketRestClientBase",
    "PolymarketSubscriptionChannel",
    "PolymarketTimeoutError",
    "PolymarketTradingClient",
    "PolymarketTransportError",
    "PolymarketWebSocketClient",
    "PolymarketWebSocketError",
    "RawMarketEvent",
    "WebSocketMessage",
    "WebSocketSubscription",
    "build_market_subscription_request",
    "build_order_execution_client",
    "build_trading_client",
    "build_user_subscription_request",
    "data_position_to_domain_position",
    "data_trade_to_domain_fill",
    "gamma_event_to_raw_market_events",
    "normalize_balance_allowance_payload",
    "normalize_fill_payload",
    "normalize_gamma_event",
    "normalize_gamma_market",
    "normalize_order_payload",
    "normalize_orderbook_payload",
    "normalize_position_payload",
    "normalize_trade_payload",
    "orderbook_payload_to_snapshot",
    "orderbook_to_domain_snapshot",
    "parse_ws_message",
]
